export const doughnuts = [
    {
        id: 1,
        name: 'Glazed',
        image: '../assets/glazed-doughnut.jpg',
        description: 'Classic Glazed Doughnut',
        specialty: false,
        price: '50¢',
    },
    {
        id: 2,
        name: 'Glazed',
        image: '../assets/glazed-doughnut.jpg',
        description: 'Classic Glazed Doughnut',
        specialty: false,
        price: '50¢',
    },
    {
        id: 3,
        name: 'Glazed',
        image: '../assets/glazed-doughnut.jpg',
        description: 'Classic Glazed Doughnut',
        specialty: false,
        price: '50¢',
    },
    {
        id: 4,
        name: 'Glazed',
        image: '../assets/glazed-doughnut.jpg',
        description: 'Classic Glazed Doughnut',
        specialty: false,
        price: '50¢',
    },
    {
        id: 5,
        name: 'Glazed',
        image: '../assets/glazed-doughnut.jpg',
        description: 'Classic Glazed Doughnut',
        specialty: false,
        price: '50¢',
    },
    {
        id: 6,
        name: 'Glazed',
        image: '../assets/glazed-doughnut.jpg',
        description: 'Classic Glazed Doughnut',
        specialty: false,
        price: '50¢',
    },
    {
        id: 7,
        name: 'Glazed',
        image: '../assets/glazed-doughnut.jpg',
        description: 'Classic Glazed Doughnut',
        specialty: false,
        price: '50¢',
    },
    {
        id: 8,
        name: 'Glazed',
        image: '../assets/glazed-doughnut.jpg',
        description: 'Classic Glazed Doughnut',
        specialty: false,
        price: '50¢',
    },
];
